# Generated by Django 3.2 on 2021-04-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210408_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.CharField(default='Preview text', max_length=255),
        ),
    ]
