# Generated by Django 3.2 on 2021-04-08 22:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='navbar_color',
            field=colorfield.fields.ColorField(default='#343A40', max_length=18),
        ),
    ]
