# Generated by Django 3.2 on 2021-04-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_navbar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_url',
            field=models.SlugField(default='error'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug_url',
            field=models.SlugField(default='error'),
            preserve_default=False,
        ),
    ]
