# Generated by Django 3.2 on 2021-04-09 23:19

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210409_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePostView',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
            ],
            bases=(django.views.generic.edit.UpdateView, 'blog.post'),
        ),
    ]
