# Generated by Django 3.2 on 2021-04-09 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_updatepostview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdatePostView',
        ),
    ]
