# Generated by Django 3.2 on 2021-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_img_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
